// ============================================================================
// API ROUTE: /api/email/send-approval-notification
// Notifies the negotiator when their approval request has been decided.
// Called internally by /api/approval/respond after a decision is recorded.
// ============================================================================

import { NextRequest, NextResponse } from 'next/server'

// ============================================================================
// SECTION 1: EMAIL TEMPLATE
// ============================================================================

interface NotificationData {
    requesterEmail: string
    requesterName: string
    approverName: string
    decision: 'approved' | 'rejected'
    decisionNote?: string
    documentName: string
    requestCategory: 'clause' | 'contract' | 'document' | null
    clauseName?: string
    studioUrl?: string
}

function generateNotificationHtml(data: NotificationData): string {
    const isApproved = data.decision === 'approved'

    const subjectLabel = data.requestCategory === 'clause'
        ? `clause "${data.clauseName || data.documentName}"`
        : data.requestCategory === 'contract'
            ? `contract sign-off`
            : `document "${data.documentName}"`

    const decisionColour = isApproved ? '#059669' : '#dc2626'
    const decisionBg = isApproved ? '#ecfdf5' : '#fef2f2'
    const decisionBorder = isApproved ? '#a7f3d0' : '#fecaca'
    const decisionLabel = isApproved ? 'APPROVED' : 'REJECTED'

    const noteBlock = data.decisionNote
        ? `<div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 16px 0;">
               <p style="color: #475569; font-size: 13px; font-weight: 600; margin: 0 0 6px;">Note from ${data.approverName}:</p>
               <p style="color: #334155; font-size: 14px; margin: 0; font-style: italic;">"${data.decisionNote}"</p>
           </div>`
        : ''

    const ctaBlock = data.studioUrl
        ? `<div style="text-align: center; margin: 28px 0;">
               <a href="${data.studioUrl}" style="display: inline-block; background: #334155; color: white; text-decoration: none; padding: 14px 28px; border-radius: 8px; font-weight: 600; font-size: 14px;">
                   ${isApproved ? 'Continue Negotiation →' : 'Return to Studio →'}
               </a>
           </div>`
        : ''

    const nextStepMessage = isApproved
        ? 'You can now proceed with this agreement.'
        : 'The approval was not granted. Please return to the studio to review your options — CLARENCE can help you explore alternative positions.'

    return `
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin: 0; padding: 0; background-color: #f1f5f9; font-family: Arial, sans-serif;">
    <div style="max-width: 600px; margin: 0 auto; padding: 40px 20px;">
        <div style="text-align: center; margin-bottom: 30px;">
            <h1 style="color: #334155; margin: 0; font-size: 28px; font-weight: 500;">CLARENCE</h1>
            <p style="color: #64748b; font-size: 11px; letter-spacing: 3px; margin: 5px 0 0; text-transform: uppercase;">The Honest Broker</p>
        </div>

        <div style="background: white; border-radius: 12px; padding: 32px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
            <p style="color: #334155; font-size: 16px; margin: 0 0 20px;">Dear ${data.requesterName},</p>

            <p style="color: #334155; font-size: 15px; margin: 0 0 20px;">
                Your approval request for the ${subjectLabel} has been reviewed by <strong>${data.approverName}</strong>.
            </p>

            <!-- Decision Badge -->
            <div style="background: ${decisionBg}; border: 1px solid ${decisionBorder}; border-radius: 8px; padding: 16px 20px; margin: 20px 0; text-align: center;">
                <span style="color: ${decisionColour}; font-size: 20px; font-weight: 700; letter-spacing: 1px;">${decisionLabel}</span>
            </div>

            ${noteBlock}

            <p style="color: #475569; font-size: 14px; margin: 0 0 20px;">
                ${nextStepMessage}
            </p>

            ${ctaBlock}

            <p style="color: #94a3b8; font-size: 12px; margin: 24px 0 0;">
                This notification was generated by CLARENCE based on the approver's decision.
            </p>
        </div>

        <div style="text-align: center; margin-top: 30px;">
            <p style="color: #94a3b8; font-size: 12px; margin: 0;">
                CLARENCE - The Honest Broker &nbsp;·&nbsp; &copy; 2026 Spike Island Studios
            </p>
        </div>
    </div>
</body>
</html>
`
}

// ============================================================================
// SECTION 2: API HANDLER
// ============================================================================

export async function POST(request: NextRequest) {
    try {
        const { Resend } = await import('resend')
        const resend = new Resend(process.env.RESEND_API_KEY)

        const body = await request.json()
        const {
            requesterEmail,
            requesterName,
            approverName,
            decision,
            decisionNote,
            documentName,
            requestCategory,
            clauseName,
            studioUrl,
        } = body

        if (!requesterEmail || !decision) {
            return NextResponse.json(
                { success: false, error: 'requesterEmail and decision are required' },
                { status: 400 }
            )
        }

        const data: NotificationData = {
            requesterEmail,
            requesterName: requesterName || 'Negotiator',
            approverName: approverName || 'Approver',
            decision,
            decisionNote,
            documentName: documentName || 'Document',
            requestCategory,
            clauseName,
            studioUrl,
        }

        const isApproved = decision === 'approved'
        const subjectLabel = requestCategory === 'clause'
            ? `Clause Approval`
            : requestCategory === 'contract'
                ? `Contract Sign-off`
                : `Document Approval`

        const { error } = await resend.emails.send({
            from: 'CLARENCE <support@clarencelegal.ai>',
            to: [requesterEmail],
            subject: `${isApproved ? '✓' : '✗'} ${subjectLabel} ${isApproved ? 'Approved' : 'Rejected'} — ${documentName}`,
            html: generateNotificationHtml(data),
        })

        if (error) {
            console.error('Resend error (approval notification):', error)
            return NextResponse.json(
                { success: false, error: error.message },
                { status: 500 }
            )
        }

        return NextResponse.json({ success: true })

    } catch (err) {
        console.error('Error sending approval notification:', err)
        return NextResponse.json(
            { success: false, error: 'Failed to send notification' },
            { status: 500 }
        )
    }
}

export async function OPTIONS() {
    return new NextResponse(null, {
        status: 200,
        headers: {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'POST, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
        },
    })
}
